apiVersion: v1
kind: Service
metadata:
  name: golang-employee-crud-service
spec:
  type: LoadBalancer
  selector:
    app: golang-employee-crud
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080